# Generated by Django 5.1.7 on 2025-03-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='project',
        ),
        migrations.AddField(
            model_name='group',
            name='projects',
            field=models.ManyToManyField(related_name='groups', to='project.project'),
        ),
    ]
