# Generated by Django 5.1.7 on 2025-03-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='project_name',
        ),
    ]
