# Generated by Django 5.1.5 on 2025-04-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_remove_group_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='projects',
        ),
    ]
