# Generated by Django 5.1.7 on 2025-04-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_group_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='project',
            new_name='projects',
        ),
    ]
