# Generated by Django 5.1.7 on 2025-04-11 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_rename_project_group_projects'),
        ('project', '0009_project_updated_by_server_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='group_projects', to='project.project'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='group_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
