# Generated by Django 5.1.7 on 2025-04-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_group_projects_alter_group_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_id',
            new_name='id',
        ),
    ]
