# Generated by Django 5.1.5 on 2025-04-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_rename_group_id_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
