# Generated by Django 2.2.5 on 2022-12-10 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=50)),
                ('projectdescription', models.TextField()),
                ('dockerid', models.CharField(max_length=50)),
                ('projectlanguage', models.CharField(max_length=50)),
                ('projectdatabase', models.CharField(max_length=50)),
                ('projectbackend', models.CharField(max_length=50)),
                ('projecttechnologymisc', models.CharField(max_length=50)),
                ('projectlink', models.CharField(max_length=50)),
                ('projectimagelink', models.CharField(max_length=50)),
                ('addeddate', models.DateField()),
                ('updateddate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
