# Generated by Django 4.1.2 on 2022-11-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=50)),
                ('projectdescription', models.TextField()),
                ('dockerid', models.CharField(max_length=50)),
                ('projectlanguage', models.CharField(max_length=50)),
                ('projectdatabase', models.CharField(max_length=50)),
                ('projectbackend', models.CharField(max_length=50)),
                ('projecttechnologymisc', models.CharField(max_length=50)),
                ('projectlink', models.CharField(max_length=50)),
                ('projectimagelink', models.CharField(max_length=50)),
                ('addeddate', models.DateField()),
                ('updateddate', models.DateField()),
            ],
        ),
    ]
