# Generated by Django 2.2.5 on 2022-12-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('faculty', 'faculty'), ('admin', 'admin')], default='faculty', max_length=100),
        ),
    ]
