# Generated by Django 4.1.2 on 2022-11-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('courseDescription', models.TextField(null=True)),
                ('courseStudentCount', models.IntegerField()),
                ('courseGroups', models.CharField(max_length=100)),
            ],
        ),
    ]
