# Generated by Django 4.1.2 on 2022-10-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseGroups',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='courseStudentCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
