# Generated by Django 5.1.7 on 2025-03-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('software_installed', models.TextField(blank=True, null=True)),
                ('idrac_info', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('stack', models.TextField(blank=True, null=True)),
                ('last_audit', models.DateField(blank=True, null=True)),
                ('currently_in_use', models.BooleanField(default=True)),
                ('repo_link', models.URLField(blank=True, null=True)),
                ('trello_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_fields', models.ManyToManyField(blank=True, related_name='project_custom_fields', to='project.customfield')),
            ],
        ),
    ]
