# Generated by Django 5.1.7 on 2025-03-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_projects'),
        ('project', '0003_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='project_groups', to='group.group'),
        ),
    ]
