# Generated by Django 5.1.7 on 2025-03-26 02:37
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_os_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='server',
            name='custom_fields',
        ),
        migrations.AlterField(
            model_name='project',
            name='last_audit',
            field=models.DateField(default=datetime.today()),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
    ]
