# Generated by Django 5.1.5 on 2025-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_custom_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_audit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
