# Generated by Django 2.2.5 on 2022-12-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
