# Generated by Django 5.1.7 on 2025-03-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_remove_group_project_name'),
        ('project', '0007_remove_project_custom_fields_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='app_user_groups', to='group.group'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='app_user_projects', to='project.project'),
        ),
    ]
