# Generated by Django 5.1.5 on 2025-03-11 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_project_installed_software_remove_project_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
