# Generated by Django 4.1.1 on 2022-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('accesslevel', models.IntegerField()),
                ('accessgranteddate', models.DateField()),
                ('accessupdateddate', models.DateField()),
                ('accessgranteduserid', models.IntegerField()),
            ],
        ),
    ]
